change to publish action

diff --git a/.github/workflows/publish-to-pypi.yaml b/.github/workflows/publish-to-pypi.yaml
--- a/.github/workflows/publish-to-pypi.yaml
+++ b/.github/workflows/publish-to-pypi.yaml
@@ -1,20 +1,30 @@
 name: Publish to PyPI
-
 on:
-  workflow_dispatch:
-    inputs:
-      version:
-        description: "Version to Publish"
-        required: true
-        default: "0.0.1"
+  release:
+    types:
+      - published
 
 jobs:
+  extract-version:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Extract version from tag
+        id: extract_version
+        run: |
+          VERSION=${GITHUB_REF#refs/tags/v}
+          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag name is not in the correct format. Expected format: v<MAJOR>.<MINOR>.<PATCH>"
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
   check-version-before:
     runs-on: ubuntu-latest
+    needs: extract-version
     steps:
       - name: Check if version already exists
         env:
-          VERSION: ${{ github.event.inputs.version }}
+          VERSION: ${{ env.VERSION }}
         run: |
           echo "Checking if version $VERSION already exists for all packages..."
 
@@ -75,7 +85,7 @@ jobs:
       # 5. Update Version
       - name: Update version in all packages
         env:
-          VERSION: ${{ github.event.inputs.version }}
+          VERSION: ${{ env.VERSION }}
         run: |
           echo "Updating version to $VERSION"
           
@@ -212,7 +222,7 @@ jobs:
       # Check if publishing succeeded
       - name: Check if version uploaded successfully
         env:
-          VERSION: ${{ github.event.inputs.version }}
+          VERSION: ${{ env.VERSION }}
         run: |
           echo "Checking if version $VERSION uploaded successfully for all packages..."
           
